version: "3.8"

services:
  app:
    container_name: green-it
    image: green-it
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
